{
 "title": "Smart Security for Industry IoT",
 "time": { "from": "2023-06-14T18:22:23.000Z", "to": "2023-06-14T19:37:14.000Z" },
 "panels": [
  {
   "title": "Detector de PPM de CO2",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "PPM" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "nivel_co2_db",
     "rawSql": "SELECT datos, fecha FROM nivel_co2_db.almacen "
    }
   ]
  },
  {
   "title": "Detector de PPM de CO2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "nivel_co2_db",
     "rawSql": "SELECT datos, fecha, id FROM nivel_co2_db.almacen  "
    }
   ]
  },
  {
   "title": "Detecciones de Movimiento",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "fizet_esp32_db",
     "rawSql": "SELECT fecha, AccelX, AccelY, AccelZ, GyroX, GyroY, GyroZ FROM fizet_esp32_db.detecciones_de_movimiento "
    }
   ]
  },
  {
   "title": "Detecciones de Distancia",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "fizet_esp32_db",
     "rawSql": "SELECT fecha, datos FROM fizet_esp32_db.detecciones_de_distancia "
    }
   ]
  },
  {
   "title": "Temperatura Raspberry ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "fizet_raspberry",
     "rawSql": "SELECT datos, fecha FROM fizet_raspberry.temperatura_raspberry "
    }
   ]
  }
 ]
}